'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4206
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class ErrorPage

	''' <summary>
	''' Head1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

	''' <summary>
	''' form1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' ApplicationTitle control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ApplicationTitle As Global.System.Web.UI.WebControls.Literal

	''' <summary>
	''' InfoMessagesPanel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal

	''' <summary>
	''' Table1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Table1 As Global.System.Web.UI.WebControls.Table

	''' <summary>
	''' TableRow2 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TableRow2 As Global.System.Web.UI.WebControls.TableRow

	''' <summary>
	''' ViewSite control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewSite As Global.System.Web.UI.WebControls.TableCell

	''' <summary>
	''' ErrorTitleLiteral control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ErrorTitleLiteral As Global.System.Web.UI.WebControls.Literal

	''' <summary>
	''' ErrorPanel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ErrorPanel As Global.System.Web.UI.WebControls.Panel

	''' <summary>
	''' ReportResult control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ReportResult As Global.System.Web.UI.WebControls.PlaceHolder

	''' <summary>
	''' ApologizeMessage control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ApologizeMessage As Global.System.Web.UI.WebControls.PlaceHolder

	''' <summary>
	''' RequestUrl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected RequestUrl As Global.System.Web.UI.WebControls.HyperLink

	''' <summary>
	''' HyperLink1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

	''' <summary>
	''' LiteralReturn control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected LiteralReturn As Global.System.Web.UI.WebControls.Literal

	''' <summary>
	''' HyperLinkReturn control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected HyperLinkReturn As Global.System.Web.UI.WebControls.HyperLink

	''' <summary>
	''' RequestUrl2 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected RequestUrl2 As Global.System.Web.UI.WebControls.HyperLink

	''' <summary>
	''' Details control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Details As Global.System.Web.UI.WebControls.Panel

	''' <summary>
	''' DetailsText control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected DetailsText As Global.System.Web.UI.WebControls.Literal

	''' <summary>
	''' ReportForm control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ReportForm As Global.System.Web.UI.WebControls.Panel

	''' <summary>
	''' DescriptionTextBox control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected DescriptionTextBox As Global.System.Web.UI.WebControls.TextBox

	''' <summary>
	''' ReportButton control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ReportButton As Global.System.Web.UI.WebControls.Button
End Class
